AWSTemplateFormatVersion: 2010-09-09
Parameters:
  KeyName:
    Description: EC2 Instance SSH Key
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  InstanceType:
    Description: EC2 instance specs configuration
    Type: String
    Default: t2.micro
    AllowedValues:
    - t2.micro
    - t2.small
    - t2.medium
Mappings:
  AMIs:
    eu-west-1:
      Name: ami-9cbe9be5
Resources:
  WordpressServer:
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html
    Type: "AWS::EC2::Instance"
    Properties: 
      # https://hackernoon.com/attach-an-iam-role-to-an-ec2-instance-with-cloudformation-33c517a8d4c3
      IamInstanceProfile: S3-Admin-Access # It might be a good idea to create this role also with CloudFormation
      ImageId: !FindInMap [ AMIs, !Ref 'AWS::Region', Name]
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-importvalue.html
      SecurityGroupIds: 
        - !ImportValue WordpressWebSGGroupId
      SubnetId: !ImportValue WordpressSubnet1 # When an autoscaling group is created we will use more than one subnet

