
AWSTemplateFormatVersion: 2010-09-09
Outputs:

  WordpressServer:
    Description: A Wordpress Server for the Wordpress project.
    Value: !Ref WordpressServer
    Export:
      Name: WordpressServer

Parameters:
  KeyName:
    Description: EC2 Instance SSH Key
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

  InstanceType:
    Description: EC2 instance specs configuration
    Type: String
    Default: t2.micro
    AllowedValues:
    - t2.micro
    - t2.small
    - t2.medium

Mappings:
  AMIs:
    eu-west-1:
      Name: ami-9cbe9be5

Resources:

  # https://aws.amazon.com/blogs/devops/authenticated-file-downloads-with-cloudformation/
  S3AdminInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"

  S3AdminRolePolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: S3Admin
      PolicyDocument:
        Statement:
        - Action:
          - "s3:*"
          Effect: Allow
          Resource: "*"
      Roles:
      - !Ref S3AdminInstanceRole

  IAMViewRolePolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: IAMView
      PolicyDocument:
        Statement:
        - Action:
          - iam:ListRoles
          Effect: Allow
          Resource: "*"
      Roles:
      - !Ref S3AdminInstanceRole

  S3AdminAccessInstanceProfile:
      Type: "AWS::IAM::InstanceProfile"
      Properties:
        Path: "/"
        Roles:
          - !Ref S3AdminInstanceRole

  WordpressServer:
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html
    Type: "AWS::EC2::Instance"
    Metadata:
      Comment: Install a Wordpress Server
      # https://stackoverflow.com/questions/46380904/cfn-init-fails-to-download-s3-file-even-though-aws-s3-cp-works
      AWS::CloudFormation::Authentication:  
        S3AccessCred:  
          type: S3  
          roleName: !Ref S3AdminInstanceRole  # I should use a read-only role here
          buckets:  
            - albertocuesta-wordpress-install    
      AWS::CloudFormation::Init:
        config:
          packages:
            yum:
              httpd: []
              php: []
              php-mysql: []
              stress: []
          sources: # For sourcing from S3 check https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-authentication.html
            "/home/ec2-user/aws-cli": "https://github.com/aws/aws-cli/tarball/master"
            "/var/www/html": "https://albertocuesta-wordpress-install.s3.amazonaws.com/wordpress.tar.gz"
            "/etc/httpd/conf": "https://albertocuesta-wordpress-install.s3.amazonaws.com/httpd.conf.tar.gz"
          files:
            "/etc/cfn/cfn-hup.conf":
              content: !Sub |
                [main]
                stack=${AWS::StackId}
                region=${AWS::Region}
              mode: "000400"
              owner: "root"
              group: "root"
            "/etc/cfn/hooks.d/cfn-auto-reloader.conf":
              content: !Sub |
                [cfn-auto-reloader-hook]
                triggers=post.update
                path=Resources.WebServerHost.Metadata.AWS::CloudFormation::Init
                action=/opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource WebServerHost --region ${AWS::Region}
          commands:
            wp-permissions:            
              command: chmod -R 755 wp-content && chown -R apache:apache wp-content
              cwd: /var/www/html
          services:
            sysvinit:
              httpd:
                enabled: 'true'
                ensureRunning: 'true'
    CreationPolicy:
      ResourceSignal:
        Timeout: PT5M
    Properties: 
      # https://hackernoon.com/attach-an-iam-role-to-an-ec2-instance-with-cloudformation-33c517a8d4c3
      IamInstanceProfile: !Ref S3AdminAccessInstanceProfile # It might be a good idea to create this role also with CloudFormation
      ImageId: !FindInMap [ AMIs, !Ref 'AWS::Region', Name]
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-importvalue.html
      SecurityGroupIds: 
        - !ImportValue WordpressWebSGGroupId
      SubnetId: !ImportValue WordpressSubnet1 # When an autoscaling group is created we will use more than one subnet
      UserData:
        "Fn::Base64":
          !Sub |
            #!/bin/bash
            yum update -y
            # cfn-init handling
            # Get the latest CloudFormation package
            yum update -y aws-cfn-bootstrap
            # Start cfn-init
            echo "/opt/aws/bin/cfn-init -s ${AWS::StackId} -r WordpressServer --region=${AWS::Region} -v"
            /opt/aws/bin/cfn-init -s ${AWS::StackId} -r WordpressServer --region=${AWS::Region} -v
            # Start up the cfn-hup daemon to listen for changes to the EC2 instance metadata
            /opt/aws/bin/cfn-hup
            # All done so signal success
            /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackId} --resource WordpressServer --region=${AWS::Region}
