AWSTemplateFormatVersion: 2010-09-09
Description: 'This template builds upon Network.yaml and EC2.yaml to create an Application Load Balancer behind a DNS Alias record -- Do not use if you are going to load the AutoScaling stacks'
Resources:
  MyELB:
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-loadbalancer.html
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      Subnets:
        - !ImportValue WordpressSubnet1
        - !ImportValue WordpressSubnet2
      SecurityGroups:
        - !ImportValue WordpressWebSG

  MyELBTargetGroup: 
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-targetgroup.html   
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      HealthCheckPath: /healthy.html
      HealthCheckPort: 80
      HealthCheckProtocol: HTTP
      HealthCheckIntervalSeconds: 6
      HealthyThresholdCount: 2
      Name: MyELBTargetGroup
      Port: 80
      Protocol: HTTP
      Targets:
        - Id: !ImportValue WordpressServer
          Port: 80
      VpcId: !ImportValue WordpressVPC

  MyELBListener:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties: 
      DefaultActions:
        - TargetGroupArn: !Ref MyELBTargetGroup
          Type: forward
      LoadBalancerArn: !Ref MyELB
      Port: 80
      Protocol: HTTP

  MyRecordSet:
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset.html
    Type: 'AWS::Route53::RecordSet'    
    Properties:
      Name: albertocuesta.click.
      HostedZoneName: albertocuesta.click.
      Type: A
      AliasTarget: 
        DNSName: !GetAtt MyELB.DNSName
        HostedZoneId: !GetAtt MyELB.CanonicalHostedZoneID
