AWSTemplateFormatVersion: 2010-09-09
Description: 'This template builds upon Network.yaml to build a MultiAZ MySQL DB'
Resources:
  MyDBSubnetGroup:
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbsubnet-group.html
    Type: "AWS::RDS::DBSubnetGroup"
    Properties: 
      DBSubnetGroupDescription: All subnets in my VPC
      DBSubnetGroupName: MyDBSubnetGroup
      SubnetIds:
        - !ImportValue WordpressSubnet1
        - !ImportValue WordpressSubnet2
  RDSInstance:
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html
    Type: "AWS::RDS::DBInstance"
    Properties:
      AllocatedStorage: 5
      DBInstanceClass: db.t2.micro
      DBSubnetGroupName: !Ref MyDBSubnetGroup # This specifies the DB Instance within the VPC that the subnets belong to.
      Engine: MySQL
      EngineVersion: 5.6.27
      MasterUsername: acloudguru
      MasterUserPassword: acloudguru
      MultiAZ: true
      Port: 3306
      PubliclyAccessible: false
      StorageType: gp2
      VPCSecurityGroups:
        - !ImportValue WordpressRDSSG
